from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Protocol, Sequence, runtime_checkable


@runtime_checkable
class MetadataRepository(Protocol):
    """Control-plane, calendar, ingestion, and provider metadata operations."""

    def save_run(self, row: Iterable[Any]) -> None: ...
    def latest_runs(self, limit: int = 20) -> List[Dict[str, Any]]: ...
    def record_provider_health(
        self, provider: str, success: bool, attempted_at: str, error: str = ""
    ) -> None: ...
    def provider_health(self) -> List[Dict[str, Any]]: ...
    def save_tushare_response(
        self, request: Dict[str, Any], rows: List[Dict[str, Any]]
    ) -> int: ...
    def upsert_economic_calendar(self, rows: List[Dict[str, Any]]) -> int: ...
    def get_economic_calendar(
        self, date_from: str, date_to: str, country: str = "US",
        impact: str = "", limit: int = 50,
    ) -> List[Dict[str, Any]]: ...
    def upsert_economic_indicators(self, rows: List[Dict[str, Any]]) -> int: ...
    def get_economic_indicators(
        self, country: str = "US", source: str = "", limit: int = 50
    ) -> List[Dict[str, Any]]: ...
    def upsert_earnings_calendar(self, rows: List[Dict[str, Any]]) -> int: ...
    def get_earnings_calendar(
        self, date_from: str, date_to: str, market: str = "",
        symbols: Optional[Sequence[str]] = None, limit: int = 50,
    ) -> List[Dict[str, Any]]: ...


@runtime_checkable
class FundamentalRepository(Protocol):
    """Transactional fundamental, statement, validation, and funnel operations."""

    def replace_fundamentals(self, report_period: str, rows: List[Dict[str, Any]]) -> int: ...
    def query_fundamentals(self, **filters: Any) -> List[Dict[str, Any]]: ...
    def replace_statement_rows(
        self, symbol: str, statement: str, rows: List[Dict[str, Any]]
    ) -> int: ...
    def get_statement_rows(
        self, symbol: str, statement: str = "", limit_periods: int = 20,
        as_of: str = "",
    ) -> List[Dict[str, Any]]: ...
    def upsert_baostock(self, row: Dict[str, Any]) -> None: ...
    def get_baostock(self, symbol: str, report_period: str) -> Optional[Dict[str, Any]]: ...
    def replace_tdx_period(self, report_period: str, rows: List[Dict[str, Any]]) -> int: ...
    def get_tdx(self, symbol: str, report_period: str) -> Optional[Dict[str, Any]]: ...
    def tdx_coverage(self) -> List[Dict[str, Any]]: ...
    def get_tdx_history(
        self, symbol: str, annual_only: bool = False, limit: int = 40,
        as_of: str = "",
    ) -> List[Dict[str, Any]]: ...
    def save_validation_results(self, rows: List[Dict[str, Any]]) -> int: ...
    def get_validation_results(
        self, symbol: str, report_period: str
    ) -> List[Dict[str, Any]]: ...
    def rebuild_validation_results(self, report_period: str, observed_at: str) -> int: ...
    def rebuild_funnel_metrics(self, rebuilt_at: str) -> int: ...
    def query_funnel_metrics(self, **filters: Any) -> List[Dict[str, Any]]: ...


@runtime_checkable
class MarketBarRepository(Protocol):
    """Online quote and time-series operations."""

    def upsert_quote(self, row: Dict[str, Any]) -> None: ...
    def get_latest_quotes(self, symbols: Sequence[str]) -> List[Dict[str, Any]]: ...
    def upsert_price_bars(
        self, symbol: str, interval: str, adjustment: str, source: str,
        ingested_at: str, bars: List[Dict[str, Any]],
        provenance: Optional[Dict[str, Any]] = None,
    ) -> int: ...
    def get_price_bars(
        self, symbol: str, interval: str, adjustment: str, limit: int
    ) -> List[Dict[str, Any]]: ...
    def get_price_bars_range(
        self, symbol: str, interval: str, adjustment: str,
        start: str, end: str, limit: int,
    ) -> tuple[List[Dict[str, Any]], bool]: ...
    def get_price_bars_page(
        self, symbol: str, interval: str, adjustment: str,
        start: str, end: str, page_size: int, after: Optional[int] = None,
    ) -> tuple[List[Dict[str, Any]], bool]: ...
    def get_price_bars_cross_section(
        self, interval: str, adjustment: str, bar_at: str, limit: int,
        symbols: Optional[Sequence[str]] = None,
    ) -> tuple[List[Dict[str, Any]], bool]: ...
    def get_price_bars_cross_section_page(
        self, interval: str, adjustment: str, bar_at: str, page_size: int,
        symbols: Optional[Sequence[str]] = None, after: Optional[str] = None,
    ) -> tuple[List[Dict[str, Any]], bool]: ...
    def get_price_bars_matrix_page(
        self, interval: str, adjustment: str, bar_ats: Sequence[str],
        symbols: Sequence[str], page_size: int,
        after: Optional[tuple[int, str]] = None,
    ) -> tuple[List[Dict[str, Any]], bool]: ...
    def get_price_bar_as_of(
        self, symbol: str, interval: str, adjustment: str,
        as_of: str, max_lookback_seconds: int,
    ) -> Optional[Dict[str, Any]]: ...
    def get_price_bars_as_of_page(
        self, interval: str, adjustment: str, as_of: str,
        max_lookback_seconds: int, symbols: Sequence[str], page_size: int,
        after: Optional[str] = None,
    ) -> tuple[List[Dict[str, Any]], bool]: ...
    def get_raw_price_bars_range(
        self, symbol: str, interval: str, adjustment: str,
        start: str, end: str, limit: int,
        sources: Optional[Sequence[str]] = None,
    ) -> tuple[List[Dict[str, Any]], bool]: ...
    def get_raw_price_bars_page(
        self, symbol: str, interval: str, adjustment: str,
        start: str, end: str, page_size: int,
        sources: Optional[Sequence[str]] = None,
        after: Optional[tuple[int, str]] = None,
    ) -> tuple[List[Dict[str, Any]], bool]: ...


@runtime_checkable
class ArtifactStore(Protocol):
    """Immutable raw artifacts and their manifests."""

    def write_json(
        self, folder: Path, dataset: str, payload: Any, source: str,
        source_url: str, raw_response_locator: str, observed_at: str,
        ingested_at: str, metadata: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]: ...
    def save_artifact(self, row: Dict[str, Any]) -> None: ...
    def save_artifacts(self, rows: List[Dict[str, Any]]) -> int: ...
    def artifact_paths(self) -> set[str]: ...
    def list_artifacts(
        self, dataset: str = "", limit: int = 100
    ) -> List[Dict[str, Any]]: ...
    def latest_artifact(
        self, dataset: str, metadata_key: str = "", metadata_value: str = ""
    ) -> Optional[Dict[str, Any]]: ...


@runtime_checkable
class ArtifactManifestRepository(Protocol):
    def save_artifact(self, row: Dict[str, Any]) -> None: ...
    def save_artifacts(self, rows: List[Dict[str, Any]]) -> int: ...
    def artifact_paths(self) -> set[str]: ...
    def list_artifacts(
        self, dataset: str = "", limit: int = 100
    ) -> List[Dict[str, Any]]: ...
    def latest_artifact(
        self, dataset: str, metadata_key: str = "", metadata_value: str = ""
    ) -> Optional[Dict[str, Any]]: ...


@dataclass(frozen=True)
class Repositories:
    metadata: MetadataRepository
    fundamentals: FundamentalRepository
    market_bars: MarketBarRepository
    artifacts: ArtifactStore
